export const GUESS_LETTER = 'GUESS_LETTER';
export const CORRECT_GUESS = 'CORRECT_GUESS';
export const INCORRECT_GUESS = 'INCORRECT_GUESS';
export const REPEAT_GUESS = 'REPEAT_GUESS';

export const GUESS_ACTIONS = new Set([
  GUESS_LETTER,
  CORRECT_GUESS,
  INCORRECT_GUESS,
  REPEAT_GUESS, ]);
