export const RESET_REMAINING = 'RESET_REMAINING';
export const INCREMENT_REMAINING = 'INCREMENT_REMAINING';
export const DECREMENT_REMAINING = 'DECREMENT_REMAINING';

export const REMAINING_ACTIONS =
new Set([ RESET_REMAINING, INCREMENT_REMAINING, DECREMENT_REMAINING, ]);
